# Generated by Django 5.2.14 on 2026-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_instructorprofile_id_alter_mahasiswa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=True),
        ),
    ]
