# Generated by Django 5.2.14 on 2026-06-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='ai_credits',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='users.instructorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
