# Generated by Django 5.2.14 on 2026-06-03 04:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_category_course_instructor_email_and_more'),
        ('payments', '0001_initial'),
        ('users', '0005_alter_instructorprofile_id_alter_mahasiswa_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaksi', 'verbose_name_plural': 'Transaksi'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='midtrans_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('course_purchase', 'Pembelian Kursus'), ('subscription_new', 'Langganan Baru'), ('subscription_renewal', 'Perpanjangan Langganan')], default='course_purchase', max_length=30, verbose_name='Jenis Transaksi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('success', 'Berhasil'), ('failed', 'Gagal'), ('expire', 'Kedaluwarsa'), ('cancel', 'Dibatalkan')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('scholar', 'Scholar — Rp49.000/bulan'), ('pro', 'Pro — Rp99.000/bulan')], max_length=20, verbose_name='Tier Berlangganan')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('suspended', 'Ditangguhkan'), ('cancelled', 'Dibatalkan'), ('expired', 'Kedaluwarsa')], default='active', max_length=20, verbose_name='Status')),
                ('saved_token_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Midtrans Saved Token ID')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mulai Periode')),
                ('current_period_end', models.DateTimeField(verbose_name='Akhir Periode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.mahasiswa', verbose_name='Mahasiswa')),
            ],
            options={
                'verbose_name': 'Langganan',
                'verbose_name_plural': 'Langganan',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.subscription', verbose_name='Langganan Terkait'),
        ),
    ]
