# Generated by Django 5.2.14 on 2026-06-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_subscription_and_transaction_type'),
        ('users', '0007_instructorprofile_ai_credits_aicredittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('course_purchase', 'Pembelian Kursus'), ('subscription_new', 'Langganan Baru'), ('subscription_renewal', 'Perpanjangan Langganan'), ('credit_purchase', 'Pembelian Kredit AI')], default='course_purchase', max_length=30, verbose_name='Jenis Transaksi'),
        ),
    ]
