/**
 * Data Perguruan Tinggi & Program Studi Indonesia
 * Sumber: PDDikti (Pangkalan Data Pendidikan Tinggi) Kemendikbudristek
 * Diperbarui untuk keperluan autocomplete pada form registrasi Belajara.
 */

// ─── UNIVERSITAS / PERGURUAN TINGGI ──────────────────────────────────────────

export const UNIVERSITAS_INDONESIA: string[] = [
  // ── PTN (Perguruan Tinggi Negeri) ────────────────────────────────────────
  "Universitas Indonesia",
  "Institut Teknologi Bandung",
  "Universitas Gadjah Mada",
  "Institut Pertanian Bogor",
  "Universitas Diponegoro",
  "Universitas Padjadjaran",
  "Universitas Airlangga",
  "Universitas Brawijaya",
  "Institut Teknologi Sepuluh Nopember",
  "Universitas Hasanuddin",
  "Universitas Andalas",
  "Universitas Sumatera Utara",
  "Universitas Sebelas Maret",
  "Universitas Negeri Yogyakarta",
  "Universitas Negeri Semarang",
  "Universitas Negeri Malang",
  "Universitas Negeri Surabaya",
  "Universitas Negeri Jakarta",
  "Universitas Negeri Medan",
  "Universitas Negeri Padang",
  "Universitas Negeri Makassar",
  "Universitas Lampung",
  "Universitas Sriwijaya",
  "Universitas Tanjungpura",
  "Universitas Mulawarman",
  "Universitas Udayana",
  "Universitas Mataram",
  "Universitas Nusa Cendana",
  "Universitas Cenderawasih",
  "Universitas Pattimura",
  "Universitas Haluoleo",
  "Universitas Sam Ratulangi",
  "Universitas Tadulako",
  "Universitas Palangka Raya",
  "Universitas Bengkulu",
  "Universitas Jambi",
  "Universitas Riau",
  "Universitas Maritim Raja Ali Haji",
  "Universitas Bangka Belitung",
  "Universitas Sultan Ageng Tirtayasa",
  "Universitas Jenderal Soedirman",
  "Universitas Jember",
  "Universitas Trunojoyo Madura",
  "Universitas Borneo Tarakan",
  "Universitas Khairun",
  "Universitas Papua",
  "Universitas Musamus",
  "Universitas Malikussaleh",
  "Universitas Samudra",
  "Universitas Teuku Umar",
  "Universitas Syiah Kuala",
  "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
  "Universitas Islam Negeri Sunan Gunung Djati Bandung",
  "Universitas Islam Negeri Sunan Kalijaga Yogyakarta",
  "Universitas Islam Negeri Maulana Malik Ibrahim Malang",
  "Universitas Islam Negeri Sunan Ampel Surabaya",
  "Universitas Islam Negeri Alauddin Makassar",
  "Universitas Islam Negeri Sumatera Utara",
  "Universitas Islam Negeri Ar-Raniry Banda Aceh",
  "Universitas Islam Negeri Raden Fatah Palembang",
  "Universitas Islam Negeri Sultan Syarif Kasim Riau",
  "Universitas Islam Negeri Walisongo Semarang",
  "Institut Teknologi Kalimantan",
  "Institut Teknologi Sumatera",
  "Institut Seni Indonesia Yogyakarta",
  "Institut Seni Indonesia Denpasar",
  "Institut Seni Indonesia Surakarta",
  "Politeknik Negeri Jakarta",
  "Politeknik Negeri Bandung",
  "Politeknik Negeri Semarang",
  "Politeknik Negeri Surabaya",
  "Politeknik Negeri Malang",
  "Politeknik Negeri Medan",
  "Politeknik Negeri Ujung Pandang",
  "Politeknik Elektronika Negeri Surabaya",
  "Politeknik Negeri Bali",

  // ── PTS Unggulan (Perguruan Tinggi Swasta) ───────────────────────────────
  "Universitas Bina Nusantara (BINUS)",
  "Universitas Pelita Harapan",
  "Universitas Trisakti",
  "Universitas Tarumanagara",
  "Universitas Atma Jaya Yogyakarta",
  "Universitas Atma Jaya Jakarta",
  "Universitas Kristen Duta Wacana",
  "Universitas Kristen Satya Wacana",
  "Universitas Kristen Maranatha",
  "Universitas Kristen Petra",
  "Universitas Islam Indonesia",
  "Universitas Muhammadiyah Jakarta",
  "Universitas Muhammadiyah Yogyakarta",
  "Universitas Muhammadiyah Surakarta",
  "Universitas Muhammadiyah Malang",
  "Universitas Muhammadiyah Surabaya",
  "Universitas Ahmad Dahlan",
  "Universitas Islam Bandung",
  "Universitas Islam Malang",
  "Universitas Al-Azhar Indonesia",
  "Universitas Gunadarma",
  "Universitas Mercubuana",
  "Universitas Esa Unggul",
  "Universitas Nasional",
  "Universitas Pancasila",
  "Universitas Pancasakti Tegal",
  "Universitas Komputer Indonesia (UNIKOM)",
  "Universitas Telkom",
  "Universitas Informatika dan Bisnis Indonesia",
  "Institut Teknologi Harapan Bangsa",
  "STMIK Amikom Yogyakarta",
  "Sekolah Tinggi Teknik Surabaya",
  "Universitas Mercu Buana Yogyakarta",
  "Universitas Dian Nuswantoro",
  "Universitas Udayana",
  "Universitas Warmadewa",
  "Universitas Hindu Indonesia",
  "Institut Bisnis dan Informatika Kesatuan",
  "Universitas Bakrie",
  "Universitas Paramadina",
  "Universitas Pradita",
  "Universitas Multimedia Nusantara",
  "Universitas Ciputra",
  "Universitas Surabaya",
  "Universitas Katolik Widya Mandala Surabaya",
  "Universitas Katolik Parahyangan",
  "Universitas Sanata Dharma",
  "Universitas De La Salle Indonesia",
  "Universitas Budi Luhur",
  "Universitas Widyatama",
  "Universitas Stikubank Semarang",
  "Universitas Teknologi Yogyakarta",
  "Universitas Nusantara PGRI Kediri",
  "Universitas PGRI Semarang",
  "Universitas Potensi Utama",
  "Universitas Bandar Lampung",
  "Universitas Indo Global Mandiri",
  "Universitas Baturaja",
  "Universitas Muhammadiyah Pontianak",
  "Universitas Tanjungpura",
  "Universitas Palangka Raya",
  "Universitas Lambung Mangkurat",
  "Universitas Islam Kalimantan",
  "Universitas Kutai Kartanegara",
  "Universitas Widya Gama Mahakam",
  "STIE Ypup Makassar",
  "Universitas Muslim Indonesia",
  "Universitas Bosowa",
  "Universitas Fajar",
  "Universitas Sulawesi Barat",
  "Universitas Halu Oleo",
  "Universitas Tadulako",
  "Universitas Sintuwu Maroso",
  "Universitas Gorontalo",
  "Universitas Negeri Gorontalo",
  "Universitas Manado",
  "Universitas Advent Indonesia",
  "Universitas Nusa Bangsa",
  "Politeknik Piksi Ganesha",
  "Institut Manajemen Telkom",
];

// ─── PROGRAM STUDI / JURUSAN ──────────────────────────────────────────────────

export const PROGRAM_STUDI_INDONESIA: string[] = [
  // ── Ilmu Komputer & Teknologi Informasi ──────────────────────────────────
  "Informatika",
  "Ilmu Komputer",
  "Sistem Informasi",
  "Teknik Informatika",
  "Teknik Komputer",
  "Teknologi Informasi",
  "Rekayasa Perangkat Lunak",
  "Keamanan Siber",
  "Kecerdasan Buatan",
  "Ilmu Data (Data Science)",
  "Bisnis Digital",
  "Komputasi Awan (Cloud Computing)",
  "Jaringan Komputer",
  "Multimedia",
  "Animasi",
  "Desain Komunikasi Visual",
  "Desain Grafis",
  "Desain Produk",
  "Desain Interaksi",
  "Sistem dan Teknologi Informasi",
  "Manajemen Informatika",
  "Komputerisasi Akuntansi",
  "D3 Teknik Komputer",
  "D3 Sistem Informasi",
  "D3 Manajemen Informatika",

  // ── Teknik ────────────────────────────────────────────────────────────────
  "Teknik Elektro",
  "Teknik Mesin",
  "Teknik Sipil",
  "Teknik Arsitektur",
  "Teknik Kimia",
  "Teknik Industri",
  "Teknik Pertambangan",
  "Teknik Perminyakan",
  "Teknik Metalurgi dan Material",
  "Teknik Nuklir",
  "Teknik Biomedik",
  "Teknik Penerbangan",
  "Teknik Perkapalan",
  "Teknik Geodesi",
  "Teknik Geofisika",
  "Teknik Geologi",
  "Teknik Fisika",
  "Teknik Tenaga Listrik",
  "Teknik Telekomunikasi",
  "Teknik Robotika",
  "Teknik Lingkungan",
  "Teknik Pangan",
  "Teknik Pertanian",
  "Teknik Perikanan",
  "Teknik Kehutanan",

  // ── Ekonomi, Bisnis & Manajemen ───────────────────────────────────────────
  "Manajemen",
  "Akuntansi",
  "Ekonomi Pembangunan",
  "Ilmu Ekonomi",
  "Ekonomi Islam",
  "Perbankan Syariah",
  "Keuangan dan Perbankan",
  "Bisnis Internasional",
  "Administrasi Bisnis",
  "Administrasi Perkantoran",
  "Pemasaran",
  "Perpajakan",
  "Logistik",
  "Manajemen Keuangan",
  "Manajemen Sumber Daya Manusia",
  "Manajemen Pemasaran",
  "Manajemen Perbankan",
  "Manajemen Operasional",
  "Kewirausahaan",

  // ── Ilmu Sosial & Humaniora ────────────────────────────────────────────────
  "Ilmu Komunikasi",
  "Hubungan Internasional",
  "Ilmu Politik",
  "Sosiologi",
  "Antropologi",
  "Ilmu Sejarah",
  "Arkeologi",
  "Filsafat",
  "Psikologi",
  "Geografi",
  "Kriminologi",
  "Kesejahteraan Sosial",
  "Administrasi Negara",
  "Administrasi Publik",
  "Ilmu Hukum",
  "Hukum Bisnis",
  "Hukum Internasional",
  "Hukum Tata Negara",
  "Kebijakan Publik",
  "Jurnalistik",
  "Hubungan Masyarakat (PR)",
  "Penyiaran (Broadcasting)",
  "Periklanan",
  "Film dan Televisi",

  // ── Pendidikan ─────────────────────────────────────────────────────────────
  "Pendidikan Matematika",
  "Pendidikan Fisika",
  "Pendidikan Kimia",
  "Pendidikan Biologi",
  "Pendidikan Bahasa Indonesia",
  "Pendidikan Bahasa Inggris",
  "Pendidikan Bahasa Arab",
  "Pendidikan Bahasa Jepang",
  "Pendidikan Bahasa Mandarin",
  "Pendidikan Sejarah",
  "Pendidikan Geografi",
  "Pendidikan Ekonomi",
  "Pendidikan Pancasila dan Kewarganegaraan",
  "Pendidikan Guru Sekolah Dasar (PGSD)",
  "Pendidikan Guru PAUD",
  "Pendidikan Teknik Informatika",
  "Pendidikan Teknik Elektro",
  "Pendidikan Jasmani",
  "Pendidikan Olahraga",
  "Bimbingan dan Konseling",
  "Teknologi Pendidikan",
  "Pendidikan Luar Biasa",
  "Pendidikan Sosiologi",
  "Pendidikan Seni Rupa",
  "Pendidikan Musik",
  "Pendidikan Tari",
  "Pendidikan Agama Islam",
  "Pendidikan Agama Kristen",
  "Pendidikan Agama Hindu",
  "Pendidikan Agama Buddha",

  // ── Sains & Matematika ─────────────────────────────────────────────────────
  "Matematika",
  "Statistika",
  "Fisika",
  "Kimia",
  "Biologi",
  "Geografi",
  "Geologi",
  "Geofisika",
  "Meteorologi",
  "Oseanografi",
  "Astronomi",
  "Biokimia",
  "Mikrobiologi",
  "Ilmu Lingkungan",
  "Ilmu Kelautan",
  "Aktuaria",

  // ── Kedokteran & Kesehatan ─────────────────────────────────────────────────
  "Pendidikan Dokter",
  "Pendidikan Dokter Gigi",
  "Farmasi",
  "Keperawatan",
  "Kebidanan",
  "Kesehatan Masyarakat",
  "Gizi",
  "Ilmu Gizi",
  "Fisioterapi",
  "Radiologi",
  "Rekam Medis",
  "Analis Kesehatan",
  "Kesehatan Lingkungan",
  "Administrasi Rumah Sakit",
  "Ilmu Biomedik",
  "Kedokteran Hewan",
  "Optometri",
  "Psikologi Klinis",
  "Epidemiologi",
  "Bioinformatika",

  // ── Pertanian, Perkebunan & Kehutanan ─────────────────────────────────────
  "Agroteknologi",
  "Agribisnis",
  "Ilmu Tanah",
  "Hama dan Penyakit Tanaman",
  "Budidaya Pertanian",
  "Teknologi Hasil Pertanian",
  "Teknologi Pangan",
  "Ilmu dan Teknologi Pangan",
  "Teknologi Pertanian",
  "Kehutanan",
  "Manajemen Hutan",
  "Silvikultur",
  "Perencanaan Wilayah",
  "Peternakan",
  "Ilmu Peternakan",
  "Nutrisi dan Makanan Ternak",
  "Budidaya Perairan",
  "Teknologi Hasil Perikanan",
  "Ilmu Kelautan",
  "Manajemen Sumber Daya Perairan",
  "Penyuluhan Pertanian",

  // ── Seni & Budaya ──────────────────────────────────────────────────────────
  "Seni Rupa",
  "Seni Tari",
  "Seni Musik",
  "Seni Drama",
  "Teater",
  "Kriya",
  "Seni Pertunjukan",
  "Seni Karawitan",
  "Etnomusikologi",
  "Bahasa dan Sastra Indonesia",
  "Bahasa dan Sastra Inggris",
  "Bahasa dan Sastra Arab",
  "Bahasa dan Sastra Jepang",
  "Bahasa dan Sastra Mandarin",
  "Bahasa dan Sastra Jawa",
  "Bahasa dan Sastra Sunda",
  "Sastra Daerah",
  "Sejarah Peradaban Islam",
  "Ilmu Al-Qur'an dan Tafsir",

  // ── Pariwisata & Perhotelan ────────────────────────────────────────────────
  "Pariwisata",
  "Perhotelan",
  "Manajemen Perhotelan",
  "Manajemen Pariwisata",
  "Destinasi Pariwisata",
  "Tata Boga",
  "Tata Rias",
  "D3 Perhotelan",
  "D3 Pariwisata",
  "Ekowisata",

  // ── Lainnya ────────────────────────────────────────────────────────────────
  "Perencanaan Wilayah dan Kota",
  "Arsitektur Lanskap",
  "Teknik Planologi",
  "Ilmu Perpustakaan",
  "Kearsipan",
  "Ilmu Informasi dan Perpustakaan",
  "Manajemen Aset",
  "Teknik Perencana",
];

// ─── Utility functions ────────────────────────────────────────────────────────

/**
 * Search universities by partial match (case-insensitive).
 * Returns max `limit` results.
 */
export function searchUniversitas(query: string, limit = 8): string[] {
  if (!query || query.trim().length < 2) return [];
  const q = query.toLowerCase().trim();
  return UNIVERSITAS_INDONESIA.filter(u =>
    u.toLowerCase().includes(q)
  ).slice(0, limit);
}

/**
 * Search study programs by partial match (case-insensitive).
 * Returns max `limit` results.
 */
export function searchProdi(query: string, limit = 8): string[] {
  if (!query || query.trim().length < 1) return [];
  const q = query.toLowerCase().trim();
  return PROGRAM_STUDI_INDONESIA.filter(p =>
    p.toLowerCase().includes(q)
  ).slice(0, limit);
}
