# Generated by Django 6.0.5 on 2026-06-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_premium_course_price'),
        ('users', '0003_user_is_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('audit', 'Audit'), ('verified', 'Verified')], default='audit', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.mahasiswa')),
            ],
            options={
                'unique_together': {('mahasiswa', 'course')},
            },
        ),
    ]
