# Generated by Django 6.0.5 on 2026-06-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('quiz', 'Quiz'), ('forum', 'Forum')], max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(default='15 mnt', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
