# Generated by Django 5.2.14 on 2026-06-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Design', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_email',
            field=models.CharField(default='tonystark@lms.com', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Tony Stark', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, default='UIUX,Design,User Research', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='/images/daniel_scott_thumbnail.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
