# Generated by Django 5.2.14 on 2026-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='IT & Software', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
